services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./server/db/:/data/db    

  client:
    build: ./myapp/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8080
    depends_on:
      - mongo
      - server

  server:
    build: ./server/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - SECRET_KEY=f+Q+hmPszLXZFdmY0VaANKq11Kin7cT1ASe0FbXG9JonuYWtQwIahqGpTLjD0Qebwyb0FVAjyMGQwtQTdgVDNQ==
      - DATABASE_URL=mongodb://mongo:27017/mydb
      - PORT=8080
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongo